### PR TITLE
Navigation Bar

### PR DESCRIPTION
**Pull request by asifaminisonline**
**Modify  Awesome books application to have:**

- A Navigation bar.

**Three content sections:**

- Books list.
- Add book form.
- Contact info.

Followed GitHub flow.
Followed best practices.

### CODE REVIEW

**Review by ha-manel — COMMENTED** [review]
# STATUS: INVALID
Hi Team
I'm sure you put a lot of effort into this project but this PR is invalid because you didn't setup `Eslint` for this project which is required since you're working with `Javascript` 👍 
Kindly fix the issue and submit the PR for review again 👍 
Best of luck!

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by asifaminisonline** [comment]
Thank you but i have configured Eslint, I have also checked the eslint
errors

**Comment by asifaminisonline** [comment]
Now I do it again thank you so much for you suggestion

**Review by rloterh — COMMENTED** [review]
Hi Team,
 
 While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
 
 ## Invalid Code Review Request
You have submitted a project, whereby ESLint linter checks are not showing on your Pull Request. Kindly ensure that **all** required linters are properly configured with regard to GitHub actions, and **all** checks are passing. Kindly request another code review when this is done.

**ESLint not showing:**
image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _Invalid Code Review Request **does not count** into the code reviews limit._
--------------------------------------------

**Pull request closed without merging**
